### PR TITLE
add logo on page

### LINKED ISSUE #3: add logo for the web app

### PR DESCRIPTION
**Pull request by syauqiahmd**
Fixes #3  , just give a comment about it... i hope you like it

### CODE REVIEW

**Comment by Rupeshiya** [comment]
@syauqiahmd  can you please give the screenshort of the page after change ?

**Comment by syauqiahmd** [comment]
screen shot 2018-10-04 at 12 11 24 pm

**Comment by Rupeshiya** [comment]
looks good @syauqiahmd  will merge it

**Comment by syauqiahmd** [comment]
thanks

**Pull request merged**
